version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 2
    reviewers:
      - ManishAradwad
    commit-message:
      prefix: chore(ci)
    groups:
      action-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
